import type { Item } from '@/types';

export const datosIniciales: Item[] = [
  {
    id: '1',
    tipo: 'pelicula',
    titulo: 'Origen (Inception)',
    genero: 'Ciencia ficción',
    anio: 2010,
    descripcion:
      'Un ladrón que roba secretos corporativos mediante tecnología de sueños compartidos recibe una misión imposible: implantar una idea en la mente de un heredero.',
    puntuacion: 8.8,
    plataforma: 'Cine',
    emoji: '🌀',
    color: '#3D3B8E',
  },
  {
    id: '2',
    tipo: 'pelicula',
    titulo: 'The Dark Knight',
    genero: 'Acción',
    anio: 2008,
    descripcion:
      'Batman debe enfrentar al Joker, un criminal anárquico que pone a prueba los límites morales de Gotham y de su propio código de justicia.',
    puntuacion: 9.0,
    plataforma: 'Cine',
    emoji: '🦇',
    color: '#1F1F1F',
  },
  {
    id: '3',
    tipo: 'pelicula',
    titulo: 'Huye (Get Out)',
    genero: 'Terror',
    anio: 2017,
    descripcion:
      'Un joven afroamericano visita a la familia de su novia y descubre una inquietante conspiración que esconde la aparente amabilidad de sus anfitriones.',
    puntuacion: 7.8,
    plataforma: 'Cine',
    emoji: '🚪',
    color: '#4B1D3F',
  },
  {
    id: '4',
    tipo: 'pelicula',
    titulo: 'Superbad',
    genero: 'Comedia',
    anio: 2007,
    descripcion:
      'Dos estudiantes de secundaria intentan conseguir alcohol para una fiesta y sobrevivir a una noche absurda antes de separarse al terminar el colegio.',
    puntuacion: 7.6,
    plataforma: 'Cine',
    emoji: '🍺',
    color: '#C9A227',
  },
  {
    id: '5',
    tipo: 'serie',
    titulo: 'Stranger Things',
    genero: 'Ciencia ficción',
    anio: 2016,
    descripcion:
      'En un pueblo de los años 80, la desaparición de un niño destapa experimentos secretos, criaturas de otra dimensión y un grupo de amigos con poderes.',
    puntuacion: 8.6,
    plataforma: 'Netflix',
    emoji: '👾',
    color: '#8B0000',
  },
  {
    id: '6',
    tipo: 'serie',
    titulo: 'Breaking Bad',
    genero: 'Drama',
    anio: 2008,
    descripcion:
      'Un profesor de química con cáncer terminal se convierte en fabricante de metanfetamina para asegurar el futuro económico de su familia.',
    puntuacion: 9.5,
    plataforma: 'Netflix',
    emoji: '⚗️',
    color: '#2E5D34',
  },
  {
    id: '7',
    tipo: 'serie',
    titulo: 'The Office',
    genero: 'Comedia',
    anio: 2005,
    descripcion:
      'Un falso documental muestra la rutina diaria de los empleados de una empresa de papel dirigida por un jefe incapaz de medir sus ocurrencias.',
    puntuacion: 8.9,
    plataforma: 'HBO Max',
    emoji: '📠',
    color: '#5A6B7B',
  },
  {
    id: '8',
    tipo: 'serie',
    titulo: 'Mindhunter',
    genero: 'Crimen',
    anio: 2017,
    descripcion:
      'Dos agentes del FBI pioneros en la psicología criminal entrevistan a asesinos en serie para entender sus mentes y crear perfiles.',
    puntuacion: 8.6,
    plataforma: 'Netflix',
    emoji: '🕵️',
    color: '#2F3A48',
  },
  {
    id: '9',
    tipo: 'juego',
    titulo: 'The Legend of Zelda: Tears of the Kingdom',
    genero: 'Aventura',
    anio: 2023,
    descripcion:
      'Link explora un Hyrule en ruinas con nuevas habilidades que le permiten combinar objetos y atravesar cielo y superficie en una aventura abierta.',
    puntuacion: 10,
    plataforma: 'Nintendo Switch',
    emoji: '🗡️',
    color: '#0E7C66',
  },
  {
    id: '10',
    tipo: 'juego',
    titulo: 'Elden Ring',
    genero: 'RPG',
    anio: 2022,
    descripcion:
      'Un extenso mundo abierto de acción y rol firmado por FromSoftware, donde un sin tierra debe restaurar el Círculo de Elden.',
    puntuacion: 9.5,
    plataforma: 'PC / Consolas',
    emoji: '⚔️',
    color: '#6B4F2E',
  },
  {
    id: '11',
    tipo: 'juego',
    titulo: 'Counter-Strike 2',
    genero: 'Shooter',
    anio: 2023,
    descripcion:
      'El clásico shooter táctico por equipos renace en el motor Source 2 con humo dinámico, mapas renovados y el mismo corazón competitivo.',
    puntuacion: 8.2,
    plataforma: 'PC (Steam)',
    emoji: '🎯',
    color: '#7A3B12',
  },
  {
    id: '12',
    tipo: 'juego',
    titulo: 'EA Sports FC 25',
    genero: 'Deportes',
    anio: 2024,
    descripcion:
      'La nueva entrega del simulador de fútbol con modos Ultimate Team, Carrera y la táctica FC IQ renovada.',
    puntuacion: 7.9,
    plataforma: 'PC / Consolas',
    emoji: '⚽',
    color: '#1E6A4A',
  },
];
